import Link from "next/link";
import { ArrowRight, TrendingUp, Clock, DollarSign, Users } from "lucide-react";
import AnimatedSection from "@/components/AnimatedSection";
import CTABanner from "@/components/CTABanner";

const caseStudies = [
  {
    company: "Meridian Logistics",
    industry: "Supply Chain & Logistics",
    color: "#00d4aa",
    challenge: "Meridian's operations team was spending 35+ hours per week manually reconciling shipment data across 4 platforms, generating reports by hand, and chasing carrier confirmations — with no predictive visibility into delays.",
    solution: "We built a unified data pipeline connecting their TMS, ERP, carrier APIs, and warehouse system into a single real-time operations dashboard. An AI forecasting layer predicted delays 72 hours in advance, and automated workflows handled carrier communication, exception routing, and daily report generation autonomously.",
    tech: ["Python", "Apache Airflow", "PostgreSQL", "OpenAI API", "Tableau", "Twilio"],
    results: [
      { icon: Clock, label: "Hours Saved Weekly", value: "35+" },
      { icon: Users, label: "FTE Equivalent Freed", value: "3 Staff" },
      { icon: TrendingUp, label: "On-Time Delivery Rate", value: "+18%" },
      { icon: DollarSign, label: "Annual Ops Savings", value: "$380K" },
    ],
    quote: "The AI doesn't just save time — it catches things we were consistently missing. We went from reactive firefighting to proactive operations in 8 weeks.",
    quotePerson: "Daniel Reyes, COO, Meridian Logistics",
    duration: "8 weeks",
  },
  {
    company: "NovaTech Solutions",
    industry: "B2B SaaS",
    color: "#4db8ff",
    challenge: "NovaTech's inside sales team was spending 60% of their time on research, data entry, and chasing unqualified leads. Their Salesforce CRM was a graveyard of stale data, and reps had no consistent way to prioritize their day.",
    solution: "We engineered an AI-powered sales intelligence layer integrated directly into Salesforce. The system auto-enriches every lead with firmographic data, scores them using a custom ML model trained on their historical wins, and routes them to the right rep with a personalized conversation brief generated by AI.",
    tech: ["Salesforce API", "GPT-4", "Python", "n8n", "Clay", "Apollo.io"],
    results: [
      { icon: TrendingUp, label: "Pipeline Conversion", value: "2.1x" },
      { icon: Clock, label: "Sales Cycle Reduction", value: "-40%" },
      { icon: DollarSign, label: "Revenue Impact Q1", value: "$1.2M" },
      { icon: Users, label: "Rep Productivity Gain", value: "+65%" },
    ],
    quote: "My reps now start every morning with a prioritized list of warm leads and exactly what to say to each one. The pipeline has never looked healthier.",
    quotePerson: "Sarah Mitchell, CEO, NovaTech Solutions",
    duration: "6 weeks",
  },
  {
    company: "Luma Health",
    industry: "Healthcare Technology",
    color: "#3ee88a",
    challenge: "Luma's patient support team was overwhelmed with repetitive intake questions, insurance verification requests, and appointment scheduling — often taking 2–4 hours to respond, leading to frustrated patients and staff burnout.",
    solution: "We built a HIPAA-compliant AI agent deployed across web chat and SMS that handles the full intake journey: answering clinical FAQs from their knowledge base, verifying insurance in real-time via payer APIs, scheduling appointments in their EHR, and escalating only complex cases to human agents — with full context transferred.",
    tech: ["Custom LLM", "Twilio", "HL7 FHIR", "Epic EHR API", "AWS Lambda", "React"],
    results: [
      { icon: Clock, label: "Avg. Response Time", value: "4 seconds" },
      { icon: TrendingUp, label: "Patient Satisfaction", value: "98%" },
      { icon: Users, label: "Support Volume Handled by AI", value: "74%" },
      { icon: DollarSign, label: "Support Cost Reduction", value: "-58%" },
    ],
    quote: "Patients are getting answers instantly, 24/7, and our staff finally has time to focus on patients who truly need human support. The ROI paid for itself in month one.",
    quotePerson: "Priya Sharma, Founder, Luma Health",
    duration: "10 weeks",
  },
];

export default function CaseStudiesPage() {
  return (
    <>
      {/* Hero */}
      <section className="relative pt-40 pb-24 overflow-hidden">
        <div className="absolute inset-0 bg-[#0b1426]" />
        <div className="absolute inset-0 opacity-20" style={{ backgroundImage: "radial-gradient(ellipse 60% 50% at 50% 50%, rgba(0,212,170,0.15) 0%, transparent 60%)" }} />
        <div className="relative max-w-7xl mx-auto px-6 text-center">
          <AnimatedSection>
            <p className="text-[#00d4aa] font-mono text-sm font-medium tracking-widest uppercase mb-4">Deep Dives</p>
            <h1 className="font-display font-bold text-5xl md:text-6xl text-white mb-6">
              Real problems.{" "}
              <span style={{ background: "linear-gradient(135deg, #00d4aa, #4db8ff)", WebkitBackgroundClip: "text", WebkitTextFillColor: "transparent", backgroundClip: "text" }}>
                Real solutions.
              </span>{" "}
              Real numbers.
            </h1>
            <p className="text-[#8ba3c7] text-xl max-w-2xl mx-auto">
              We document every engagement in detail — the problem, our approach, the technology, and the exact results. No vanity metrics.
            </p>
          </AnimatedSection>
        </div>
      </section>

      {/* Case Studies */}
      <section className="py-8 pb-24 bg-[#080e1c]">
        <div className="max-w-5xl mx-auto px-6 space-y-16">
          {caseStudies.map((cs, i) => (
            <AnimatedSection key={cs.company} delay={i * 100}>
              <div className="rounded-3xl overflow-hidden" style={{ border: "1px solid rgba(77,184,255,0.12)" }}>
                {/* Header */}
                <div className="px-8 md:px-12 py-8" style={{ background: `linear-gradient(135deg, ${cs.color}10, rgba(77,184,255,0.05))`, borderBottom: "1px solid rgba(77,184,255,0.1)" }}>
                  <div className="flex items-center justify-between flex-wrap gap-4">
                    <div>
                      <p className="font-mono text-xs font-medium mb-2 uppercase tracking-widest" style={{ color: cs.color }}>{cs.industry}</p>
                      <h2 className="font-display font-bold text-3xl text-white">{cs.company}</h2>
                    </div>
                    <div className="flex items-center gap-2 px-4 py-2 rounded-full text-sm font-mono" style={{ background: `${cs.color}12`, border: `1px solid ${cs.color}30`, color: cs.color }}>
                      <Clock size={14} />
                      Delivered in {cs.duration}
                    </div>
                  </div>
                </div>

                <div className="px-8 md:px-12 py-10 bg-[rgba(17,30,58,0.6)]">
                  {/* Challenge & Solution */}
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mb-10">
                    <div>
                      <h3 className="font-display font-semibold text-white mb-3 flex items-center gap-2">
                        <span className="w-2 h-2 rounded-full bg-red-400" />
                        The Challenge
                      </h3>
                      <p className="text-[#8ba3c7] text-sm leading-relaxed">{cs.challenge}</p>
                    </div>
                    <div>
                      <h3 className="font-display font-semibold text-white mb-3 flex items-center gap-2">
                        <span className="w-2 h-2 rounded-full" style={{ background: cs.color }} />
                        Our Solution
                      </h3>
                      <p className="text-[#8ba3c7] text-sm leading-relaxed">{cs.solution}</p>
                    </div>
                  </div>

                  {/* Results */}
                  <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-10">
                    {cs.results.map((r) => (
                      <div key={r.label} className="rounded-xl p-5 text-center" style={{ background: "rgba(11,20,38,0.8)", border: `1px solid ${cs.color}20` }}>
                        <r.icon size={20} className="mx-auto mb-2 opacity-60" style={{ color: cs.color }} />
                        <p className="font-display font-bold text-2xl text-white mb-1">{r.value}</p>
                        <p className="text-[#8ba3c7] text-xs">{r.label}</p>
                      </div>
                    ))}
                  </div>

                  {/* Tech Stack */}
                  <div className="mb-8">
                    <p className="text-xs font-mono uppercase tracking-widest text-[#8ba3c7] mb-3">Technology Stack</p>
                    <div className="flex flex-wrap gap-2">
                      {cs.tech.map((t) => (
                        <span key={t} className="px-3 py-1.5 rounded-lg text-xs font-mono" style={{ background: "rgba(77,184,255,0.06)", border: "1px solid rgba(77,184,255,0.12)", color: "#8ba3c7" }}>{t}</span>
                      ))}
                    </div>
                  </div>

                  {/* Quote */}
                  <div className="rounded-xl p-6" style={{ background: `${cs.color}08`, border: `1px solid ${cs.color}20` }}>
                    <p className="text-white text-base leading-relaxed mb-3 italic">"{cs.quote}"</p>
                    <p className="font-mono text-sm" style={{ color: cs.color }}>— {cs.quotePerson}</p>
                  </div>
                </div>
              </div>
            </AnimatedSection>
          ))}
        </div>
      </section>

      <CTABanner
        headline="Your company could be the next case study"
        sub="We're selective about the projects we take on, which is why every engagement delivers results worth documenting."
        primaryLabel="Apply to Work With Us"
        secondaryLabel="View Our Portfolio"
        secondaryHref="/portfolio"
      />
    </>
  );
}
